language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=luajit

before_install:
  - source .travis/setenv_lua.sh
  - pip install --user cpp-coveralls
  - luarocks install Lua-cURL         --server=https://luarocks.org/dev
  - luarocks install luacov-coveralls --server=https://luarocks.org/dev
  - luarocks install lunitx

install:
  - luarocks install bit32
  - luarocks install luafilesystem
  - sudo apt-get install -qq liblz4-dev

script:
  - git clone https://github.com/ValkyrieRBXL/Valkyrie_CI .Builder/
  - ln -s . .Builder/build/MainModule.mod.lua
  - ./Builder/Test.lua -- .

after_success:
  - coveralls -b .. -r .. -i ./src --dump c.report.json
  - luacov-coveralls -j c.report.json -v

notifications:
  email:
    on_success: change
    on_failure: always
